# -*- coding: utf-8 -*-
"""KNN.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wqJ1bniZrOXjU9qznscHn-sR1Cnzvdz5
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import confusion_matrix, precision_score, recall_score, accuracy_score

df=pd.read_csv("/content/diabetes.csv")
df

df.head()

df.tail()

df.info()

df.describe()

X= df.drop('Outcome', axis=1)
y= df['Outcome']

scaler=StandardScaler()
X_scaled= scaler.fit_transform(X)

X_train, X_test, y_train, y_test = train_test_split(X_scaled, y, random_state=42, test_size=0.2)

knn=KNeighborsClassifier(n_neighbors=5)
knn.fit(X_train, y_train)
y_pred= knn.predict(X_test)

cm=confusion_matrix(y_test, y_pred)
cm

from sklearn.metrics import accuracy_score
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)

precision = precision_score(y_test, y_pred)
precision

recall = recall_score(y_test, y_pred)
recall

plt.figure(figsize=(6,4))
sns.heatmap(cm, annot=True, fmt="d", cmap = "Blues", xticklabels=["Non-diabetic", "Diabetic"], yticklabels=["Non-diabetic", "Diabetic"])
plt.xlabel=("predicted")
plt.ylabel=("Actual")
plt.title=("Confusion_matrix")
plt.show

